baseURL = "https://www.ethohampton.com"
languageCode = "en-us"
title = "Ethan Hampton"
theme="EMH_Green_Theme"
sectionPagesMenu = "main"

pygmentsCodefencesGuessSyntax=true
pygmentsCodeFences=true
pygmentsStyle="tango"

enableGitInfo=true #use git for modification date data 

[pagination]
  pagerSize = 10 #How many posts per page

[params]
  description = "Ethan Hampton's Website"
  author = "Ethan Hampton"
  sideMenuTAI = true
  sideMenuNeat = true
  ignoredMenuTypes = ["images","pages","posts","goverment"]


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "#"
    weight = 2
    [[menu.main]]
      parent = "projects"
      identifier = "infrastructure"
      name = "Infrastructure"
      title = "Infrastructure"
      url = "/pages/infrastructure/"
      weight = 1
    [[menu.main]]
      parent = "projects"
      identifier = "shorts"
      name = "Shorts"
      title = "Shorts"
      url = "https://neat.ethohampton.com/shorts"
      weight = 2
    [[menu.main]]
      parent = "projects"
      identifier = "other_projects"
      name = "Other Projects"
      title = "Other Projects"
      url = "/pages/projects/"
      weight = 3
  [[menu.main]]
    identifier = "resume"
    name = "Résumé"
    title = "Résumé"
    url = "/pages/ethan-hampton-resume/"
    weight = 3
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/posts/"
    weight = 6
#  [[menu.main]]
#    identifier = "projects"
#    name = "Projects"
#    title = "My Projects"
#  [[menu.main]]
#    parent = "projects"
#    identifier = "Rules"
#    name = "My Rules"
#    title = "My Rules For Life"
#    url = "/rules.html"

[permalinks]
  posts = "/:year/:month/:slug/"
	


