---
label: Default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: text
  name: description
  label: Description
  config:
    required: false
