---
label: Default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: text
  name: description
  label: Description
  config:
    required: false
pages:
- content/posts/2019/the-tip-of-the-iceberg.md
- content/posts/2019/so-you-want-to-start-a-blog.md
- content/posts/2019/too-much-to-stomach.md
- content/posts/2019/what-i-learned-from-deploying-a-pwa-to-my-high-school.md
- content/posts/2019/02/the-lagoon.md
- content/posts/2019/01/Short_or_Long_Term.md
- content/posts/2019/04/prom.md
