name: Build and Deploy Hugo

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
        fetch-depth: '0'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.82.0'
        extended: true
        
    - name: Run the hugo build
      run: hugo -v --minify

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-vzr --delete'
        options: ''
        ssh_options: ''
        src: 'public/'
        dest: 'emh-web-deploy@${{ secrets.DEPLOY_SERVER }}:/var/www/html/ethohampton.com'
