name: Build Hugo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install Git LFS
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt-get install git-lfs -y

    - name: Checkout  
      uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'
        extended: true
        
    - name: Add theme and pull LFS files
      run: |
        git submodule update --init --recursive
        git lfs pull

    - name: Run the hugo build
      run: hugo -v --minify

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: site
        # Directory containing files to upload
        path: public
