name: Build and Deploy Hugo

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
        fetch-depth: '0'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.96.0'
        extended: true
        
    - name: Run the Hugo build
      run: hugo -v --minify

    - name: Create .gz files
      run: find public/ -type f \( -name '*.html' -o -name '*.js' -o -name '*.css' -o -name '*.xml' -o -name '*.svg' \) -exec gzip -v -k -f -n --best {} \;

    - name: Deploy to server
      id: deploy
      uses: EMH333/action-rsyncer@v1.3
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-vzcr --delete'
        options: ''
        ssh_options: ''
        src: 'public/'
        dest: 'emh-web-deploy@${{ secrets.DEPLOY_SERVER }}:/var/www/html/ethohampton.com'
