name: Build Hugo

on:
  push:
    branches-ignore: 
      - 'main' #Already building if on main, no point in building again

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout  
      uses: actions/checkout@v3
      with:
        #lfs: true
        submodules: true

    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-v1-${{ hashFiles('.lfs-assets-id') }}
        restore-keys: | # can restore old caches because they'll get updated with new files on pull
            ${{ runner.os }}-lfs-v1

    - name: Git LFS Pull
      run: git lfs pull

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest' #note we are using the latest version here for testing, need to be updated manually for main
        extended: true

    - name: Run the hugo build
      run: hugo --logLevel debug --minify

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: site
        # Directory containing files to upload
        path: public
